### PR TITLE
Handle exceptions which can make GetServerRules to fail.

### LINKED ISSUE #10: Getting server rules fails entirely if it has invalid times.
**Describe the bug**
When querying a server with an invalid time value, fetching the server rules will launch an exception.

**To Reproduce**
Try getting the rules for a server with an invalid datetime (in this case, while going through a lot of IP's, I first found this failure with `193.203.39.216:7777`)
imagen

**Expected behavior**
If a date is invalid, it should return some default value or trim it down to a valid minimum or maximum rather than fail the entire rule fetch operation

### PR DESCRIPTION
**Pull request by markski1**
### Description of change
- Addresses issue in which invalid date strings (which are common in roleplay and cnr servers) cause an unhandled exception, by returning a time of 0 if the read time cannot be parsed. This is the best possible fix I think. It will return a false hour, but a lot better than failing the function completely. Fixes #10 
- Addresses issue where invalid Uris cause an unhandled exception if Weburl is invalid. It will try to use the entire value as the uri, and if that fails, it'll just return sa-mp.com as the Uri. This can mean returning an inaccurate Weburl, but again, better than failing the entire function.

NOTES:

- Tested locally on my computer after installing .NET 5 and the rules test worked fine.
- In my opinion, for future reference, I think the time should just be handled as a string instead of converting it to DateTime. In SA-MP times and dates seem to be mostly for show than for actual use. In fact, I'd strongly prefer this was the case, for what it's worth. But this is a personal preference and unrelated to the pull request at hand.

### Pull-Request Checklist

- [x] Code is up-to-date with the `master` branch
- [x] All tests are passed (if tests fail due to timeout, try running the tests later or run them sequentially)
- [x] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change - N/A
- [ ] Documentation (README.md) has been updated to reflect this change - N/A

### CODE REVIEW

**Comment by markski1** [comment]
I have also added a condition for the byte type parsing to return a default value, because, again, server owners don't follow standards and stuff like this happens:

imagen

File: Src/SampQuery.cs [hunk 1]
```diff
@@ -387,9 +387,29 @@ private string CollectRconAnswerFromByteArray(byte[] data)
...
+                            {
+                                try
+                                {
+                                    val = Convert.ChangeType(value, property.PropertyType, CultureInfo.InvariantCulture);
+                                }
+                                catch
+                                {
+                                    // the value could not be parsed, try to get a default.
+                                    value = "0";
+                                    val = Convert.ChangeType(value, property.PropertyType, CultureInfo.InvariantCulture);
```
Comment (justmavi) [inline Src/SampQuery.cs:419]: That's illogical

File: Src/Utils/Helpers.cs [hunk 2]
```diff
@@ -12,5 +12,27 @@ public static void CheckNullOrEmpty(string value, string parameterName)
...
+                    // If that fails, then try to parse with http
+                    return new Uri("http://" + value, UriKind.Absolute);
+                }
+                catch
+                {
+                    // If that fails, then just return sa-mp.com because we can't return nothing
+                    return new Uri("http://sa-mp.com/", UriKind.Absolute);
+                }
+            }
+        }
```
Comment (justmavi) [inline Src/Utils/Helpers.cs]: You can use Uri.TryCreate instead of many try..catch blocks

File: Src/SampQuery.cs [hunk 3]
```diff
@@ -387,9 +387,29 @@ private string CollectRconAnswerFromByteArray(byte[] data)
...
+                            else if (property.PropertyType == typeof(Uri)) val = Helpers.TryParseWeburl(value);
+                            else if (property.PropertyType == typeof(DateTime))
+                            {
+                                bool success = TimeSpan.TryParse(value, out TimeSpan parsedTime);
+                                if (!success)
+                                {
+                                    parsedTime = TimeSpan.FromHours(0);
+                                }
+                                val = DateTime.Today.Add(parsedTime);
+                            }
```
Comment (justmavi) [inline Src/SampQuery.cs:408]: Can be moved to the helper

**Comment by justmavi** [comment]
Hello.
Thank you for your contribution. I'll check it out later. If you can fix my remarks, please do it. Otherwise I'll do it myself later.

**Comment by markski1** [comment]
All addressed, except for defaulting byte convert to 0. I understand it's illogical, but I don't know how else to handle that. 

As you can see in my comment's screenshot, it's because some servers are using text in the weather field, there is no logical way to parse that into a number, so I figured it should return 0 instead of just crashing outright
